#!/bin/sh

# osinfo - show information about the operating system

# You can place this script in /etc/update-motd.d/.

#shellcheck source=/dev/null
OS=$(
  . /etc/os-release
  echo "$PRETTY_NAME"
)
KERNEL=$(uname -rv)

echo "$OS $KERNEL"
uptime -p
